In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1440, 9132, 7806, 4696],
 [1440, 9132, 7806, 1056],
 [1440, 6525, 7806, 3110],
 [8341, 8582, 8500, 4740, 7179],
 [8341, 8582, 8500, 4740, 394],
 [5217, 1440, 9042, 7806, 2419],
 [816, 1619, 5930, 4740]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1440 9132 7806 4696]
 [   0    0    0    0 1440 9132 7806 1056]
 [   0    0    0    0 1440 6525 7806 3110]
 [   0    0    0 8341 8582 8500 4740 7179]
 [   0    0    0 8341 8582 8500 4740  394]
 [   0    0    0 5217 1440 9042 7806 2419]
 [   0    0    0    0  816 1619 5930 4740]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\rohan\CHURN-MODELLING\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 282ms/step


array([[[-4.17517312e-02,  4.40917127e-02,  5.36645576e-03,
          3.43727358e-02,  1.31017677e-02,  3.54604013e-02,
         -3.08482889e-02, -2.20157262e-02, -1.05046257e-02,
         -2.57635359e-02],
        [-4.17517312e-02,  4.40917127e-02,  5.36645576e-03,
          3.43727358e-02,  1.31017677e-02,  3.54604013e-02,
         -3.08482889e-02, -2.20157262e-02, -1.05046257e-02,
         -2.57635359e-02],
        [-4.17517312e-02,  4.40917127e-02,  5.36645576e-03,
          3.43727358e-02,  1.31017677e-02,  3.54604013e-02,
         -3.08482889e-02, -2.20157262e-02, -1.05046257e-02,
         -2.57635359e-02],
        [-4.17517312e-02,  4.40917127e-02,  5.36645576e-03,
          3.43727358e-02,  1.31017677e-02,  3.54604013e-02,
         -3.08482889e-02, -2.20157262e-02, -1.05046257e-02,
         -2.57635359e-02],
        [ 3.12252380e-02,  2.97585465e-02,  4.74205874e-02,
          9.87485796e-03, -2.98177078e-03,  4.12522592e-02,
         -4.65449467e-02, -2.33159419e-02, -7.345832

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 1440, 9132, 7806, 4696], dtype=int32)